version: '3.8'

services:
  redis:
    image: redis:7.0
    container_name: orgtalk-redis
    restart: always
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - orgtalk-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s       # 느슨하게
      timeout: 10s
      retries: 10

  mongodb:
    image: mongo:latest
    container_name: orgtalk-mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - orgtalk-net
    healthcheck:
      test:
        - "CMD"
        - "mongo"
        - "--username"
        - "${MONGODB_USERNAME}"
        - "--password"
        - "${MONGODB_PASSWORD}"
        - "--eval"
        - "db.adminCommand('ping')"
      interval: 30s
      timeout: 10s
      retries: 10

  kafka:
    image: bitnami/kafka:latest
    container_name: orgtalk-kafka
    restart: always
    environment:
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CREATE_TOPICS=chat-messages:5:1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NUM_PARTITIONS=5
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - orgtalk-net
    healthcheck:
      test: [ "CMD-SHELL", "echo > /dev/tcp/localhost/9092" ]
      interval: 30s
      timeout: 10s
      retries: 10

  main-server:
    image: ${DOCKER_USERNAME}/main-server:latest
    container_name: orgtalk-main-server
    restart: always
    networks:
      - orgtalk-net
    depends_on:
      redis:
        condition: service_started
      kafka:
        condition: service_started
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKERS=kafka:9092
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - FRONTEND_REDIRECT_URI=${FRONTEND_REDIRECT_URI}

  chat-server:
    image: ${DOCKER_USERNAME}/chat-server:latest
    container_name: orgtalk-chat-server
    restart: always
    networks:
      - orgtalk-net
    depends_on:
      mongodb:
        condition: service_started
      kafka:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKERS=kafka:9092
      - JWT_ORIGIN_KEY=${JWT_ORIGIN_KEY}
      - JWT_APP_KEY=${JWT_APP_KEY}

  frontend:
    image: ${DOCKER_USERNAME}/frontend:latest
    container_name: orgtalk-frontend
    restart: always
    networks:
      - orgtalk-net
    depends_on:
      - main-server
      - chat-server
    environment:
      - REACT_APP_MAIN_SERVER_URL=/api/main
      - REACT_APP_CHAT_SERVER_URL=/api/chat
      - FRONTEND_REDIRECT_URI=${FRONTEND_REDIRECT_URI}

  nginx:
    image: nginx:alpine
    container_name: orgtalk-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - orgtalk-net
    depends_on:
      - frontend
      - main-server
      - chat-server
    healthcheck:
      test:
        - "CMD"
        - "wget"
        - "--quiet"
        - "--tries=1"
        - "--spider"
        - "http://localhost/health"
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis-data:
    driver: local
  mongo-data:
    driver: local
  kafka-data:
    driver: local

networks:
  orgtalk-net:
    driver: bridge
