version: '3.8'

services:
  redis:
    image: redis:7.0
    container_name: orgtalk-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command:
      - redis-server
      - --appendonly yes
    networks:
      - orgtalk-net

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: orgtalk-redis-exporter
    restart: always
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis:6379
    networks:
      - orgtalk-net
    depends_on:
      - redis

  mongo-exporter:
    image: percona/mongodb_exporter:0.39.0
    container_name: orgtalk-mongo-exporter
    restart: always
    ports:
      - "9216:9216"
    environment:
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/?authSource=admin
    command:
      - "--collect-all"
      - "--compatible-mode"
    networks:
      - orgtalk-net
    depends_on:
      - mongodb

  prometheus:
    image: prom/prometheus:latest
    container_name: orgtalk-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - orgtalk-net
    depends_on:
      - redis-exporter
      - mongo-exporter
  influxdb:
    image: influxdb:1.8
    container_name: orgtalk-influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - orgtalk-net

  grafana:
    image: grafana/grafana:latest
    container_name: orgtalk-grafana
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - orgtalk-net
    depends_on:
      - prometheus
      - influxdb

  mongodb:
    image: mongo:latest
    container_name: orgtalk-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db
    networks:
      - orgtalk-net

  kafka:
    image: bitnami/kafka:latest
    container_name: orgtalk-kafka
    restart: always
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_NUM_PARTITIONS=5
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - orgtalk-net


volumes:
  redis-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  influxdb-data:
    driver: local
  mongo-data:
    driver: local
  kafka-data:
    driver: local

networks:
  orgtalk-net:
    driver: bridge
