version: '3.8'

services:
  redis:
    image: redis:7.0
    container_name: orgtalk-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command:
      - redis-server
      - --appendonly yes
    networks:
      - orgtalk-net

volumes:
  redis-data:
    driver: local

networks:
  orgtalk-net:
    driver: bridge
