version: '3.8'

services:
  redis:
    image: redis:7.0
    container_name: orgtalk-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command:
      - redis-server
      - --appendonly yes
    networks:
      - orgtalk-net

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: orgtalk-redis-exporter
    restart: always
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis:6379
    networks:
      - orgtalk-net
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:latest
    container_name: orgtalk-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - orgtalk-net
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    depends_on:
      - redis-exporter

  influxdb:
    image: influxdb:1.8
    container_name: orgtalk-influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - orgtalk-net

  grafana:
    image: grafana/grafana:latest
    container_name: orgtalk-grafana
    restart: always
    ports:
      - "3001:3000"      # 호스트 3001번 → 컨테이너 3000번
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - orgtalk-net
    depends_on:
      - prometheus
      - influxdb

volumes:
  redis-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  influxdb-data:
    driver: local

networks:
  orgtalk-net:
    driver: bridge
