server:
  port: 8081
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: chat-server

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:orgTalk}
      username: ${MONGODB_USERNAME:admin}
      password: ${MONGODB_PASSWORD:admin123}
      authentication-database: admin

    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    usrname: guest
    password: guest
    virtual-host: /

custom:
  jwt:
    duration:
      access: 360000         # 60분 (밀리초)
      refresh: 86400000      # 24시간 (밀리초)
    secrets:
      origin-key: ${JWT_ORIGIN_KEY}
      app-key: ${JWT_APP_KEY}

logging:
  level:
    org.springframework.web.socket.messaging.StompSubProtocolHandler: DEBUG
    org.springframework.web.socket.server: DEBUG
    org.springframework.web.socket.sockjs: DEBUG
    org.springframework.messaging: DEBUG
